dataset:
   exp_name: '0617'
   in_MM: True
### 4.77mm
cam:
   R:
      rows: 3
      cols: 3
      dt: d
      data: [ 0.9999 ,  -0.0054  , -0.0086,
    0.0054 ,   1.0000 ,  -0.0005,
    0.0086,    0.0004,    1.0000]

   T:
      rows: 1
      cols: 3
      dt: d
      data: [ 5.5160 ,   0.0481,   -0.0733]
   M1:
      rows: 3
      cols: 3
      dt: d
      data: [   814.5251 ,        0 , 557.9058,
         0,  819.2740 , 310.3477,
   0,0,1.0000 ]
   D1:
      rows: 1
      cols: 5
      dt: d
      data: [  -0.3392 ,   0.4098 ,        0     ,    0     ,    0 ]
   M2:
      rows: 3
      cols: 3
      dt: d
      data: [   823.6621 ,        0 , 475.6436,
         0 , 827.7783,  306.1303,0,0,1.0000 ]
   D2:
      rows: 1
      cols: 5
      dt: d
      data: [ -0.3731 ,   0.4762, 0, 0, 0. ]
   RECT_M1:
      rows: 3
      cols: 3
      dt: d
      data: [   801.57991404 ,        0 , 583.56089783,
         0,  801.57991404 , 309.78999329,
   0,0,1.0000 ]
   RECT_M2:
      rows: 3
      cols: 3
      dt: d
      data: [   801.57991404 ,        0 , 491.24100494,
         0,  801.57991404 , 309.78999329,
   0,0,1.0000 ]

   dist_coeff: